#  ██████╗ ██╗███████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗██████╗ ██╗  ██╗
# ██╔════╝ ██║██╔════╝╚══██╔══╝██╔════╝██╔═══██╗██╔══██╗██╔════╝╚════██╗██║  ██║
# ██║  ███╗██║█████╗     ██║   ██║     ██║   ██║██║  ██║█████╗   █████╔╝███████║
# ██║   ██║██║██╔══╝     ██║   ██║     ██║   ██║██║  ██║██╔══╝  ██╔═══╝ ╚════██║
# ╚██████╔╝██║██║        ██║   ╚██████╗╚██████╔╝██████╔╝███████╗███████╗     ██║
#  ╚═════╝ ╚═╝╚═╝        ╚═╝    ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚══════╝     ╚═╝
# Plugin made by QuangDev05.
# Plugin made in Vietnam.
# Facebook: https://www.facebook.com/quangdev05
# Discord: quangdev05.
# Discord Community: https://discord.gg/4SGhHNmhE8
# Github: https://github.com/QuangDev05/GiftCode24
# Spigot: https://www.spigotmc.org/resources/giftcode24.117453/
# BuiltByBit: https://builtbybit.com/resources/giftcode24.46671/

check-update: true # false để tắt.

messages:
  invalid-code: "Mã quà tặng bạn đã nhập không hợp lệ."
  code-expired: "Mã quà tặng bạn nhập đã hết hạn."
  max-uses-reached: "Mã quà tặng đã hết lượt sử dụng."
  max-uses-perip: "Mã quà tặng này đã được sử dụng quá số lần cho phép từ địa chỉ IP của bạn."
  code-disabled: "Mã quà tặng bạn nhập hiện đã bị vô hiệu hóa."
  code-redeemed: "Bạn đã đổi mã quà tặng thành công!"
  code-already-redeemed: "Bạn đã nhập mã này quá số lần quy định."
  not-enough-playtime: "Bạn cần chơi ít nhất {required} phút để sử dụng mã này. Hiện tại bạn mới chơi được {current} phút."

