name: GiftCode24
version: '${project.version}'
main: quangdev05.giftcode24.GiftCode24
api-version: 1.13
folia-supported: true
load: POSTWORLD
author: QuangDev05
description: "GiftCode24 is a powerful gift code management plugin for Minecraft servers."
website: https://github.com/quangdev05
softdepend: [bStats]

commands:
  giftcode:
    usage: /<command>
    permission: giftcode.admin
    aliases: [gc]
  code:
    usage: /<command>

permissions:
  giftcode.admin:
    default: op
  giftcode.player:
    default: true
